# -*- coding: utf-8 -*-
"""proj_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-MKmDeVzVtfpIO9Y4UzZsUTqSXJYpFc
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import figure
import math

v0_df = pd.read_csv('ex2_v0_matrix.csv')
v0_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = v0_df.iloc[: , 0]

# get widths (first column)
widths = v0_df.columns.values
widths = np.delete(widths, 0)
widths = pd.Series(widths)

# remove first column to not disturb visualization
v0_df = v0_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in v0_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]
plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("v0")
plt.show()

v4a_df = pd.read_csv('ex2_v4a_matrix.csv')
v4a_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = v4a_df.iloc[: , 0]

# get widths (first column)
widths = v4a_df.columns.values
widths = np.delete(widths, 0)
widths = pd.Series(widths)

# remove first column to not disturb visualization
v4a_df = v4a_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in v4a_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]
plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("v4a")
plt.show()

v4b_df = pd.read_csv('ex2_v4b_matrix.csv')
v4b_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = v4b_df.iloc[: , 0]

# get widths (first column)
widths = v4b_df.columns.values
widths = np.delete(widths, 0)
widths = pd.Series(widths)

# remove first column to not disturb visualization
v4b_df = v4b_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in v4b_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]
plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("v4b")
plt.show()

v5_df = pd.read_csv('ex2_v5_matrix.csv')
v5_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = v5_df.iloc[: , 0]

# get widths (first column)
widths = v4b_df.columns.values
widths = pd.Series(widths)

# remove first column to not disturb visualization
v5_df = v5_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in v5_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]

plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("v5")
plt.show()

v6_df = pd.read_csv('ex1_v6_matrix.csv')
v6_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = v6_df.iloc[: , 0]

# get widths (first column)
widths = v4b_df.columns.values
widths = pd.Series(widths)

# remove first column to not disturb visualization
v6_df = v6_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in v6_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]

plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("v6")
plt.show()

v7_df = pd.read_csv('ex2_v7_matrix.csv')

v7_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = v7_df.iloc[: , 0]

# get widths (first column)
widths = v4b_df.columns.values
widths = pd.Series(widths)

# remove first column to not disturb visualization
v7_df = v7_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in v7_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]

plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("v7")
plt.show()

all_df = pd.read_csv('ex2_all_matrix.csv')

all_df.fillna(0, inplace=True)

# get lengths (first row)
lengths = all_df.iloc[: , 0]

# get widths (first column)
widths = v4b_df.columns.values
widths = pd.Series(widths)

# remove first column to not disturb visualization
all_df = all_df.iloc[: , 1:]

f, ax = plt.subplots(figsize=(8,8))
all_valid = []
all_invalid = []
for index, row in all_df.iterrows():
    for i,x in enumerate(row):
        # print(i)
        if x!=0:
            all_valid.append([index,i])
        if x==0:
            all_invalid.append([index,i])

all_valid = pd.DataFrame(all_valid)
all_invalid = pd.DataFrame(all_invalid)

plt.scatter(all_valid[0],all_valid[1], marker=",", color='#5CB85C')
plt.scatter(all_invalid[0] ,all_invalid[1], marker=",", color='#DC3545')
plt.xlabel('Length')
plt.ylabel('Width')
xlabels = lengths[::math.floor(len(lengths)/8)]
ylabels = widths[::math.floor(len(widths)/8)]

plt.xticks(xlabels.index, xlabels)
plt.yticks(ylabels.index, ylabels)
plt.gca().invert_yaxis()
print("all")
plt.show()